table orders
	lineageTag: f6ec8f0b-8014-40fb-9a09-a7df5cb821b2

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: 7cb249d3-8a68-4287-b2c3-5ff6a2e0db75
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 9bd61404-7995-405b-9944-367682ac7b7d
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: dd3e0a3e-619b-4fad-af70-7aba2ea9132b
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b87acc7d-a9c5-4820-9d03-7dea16fd64ec
		summarizeBy: none
		sourceColumn: order_date

		variation Variation
			isDefault
			relationship: d1fb7be1-f52d-474d-8897-4cd74d692a2c
			defaultHierarchy: LocalDateTable_288bf2f8-6cb1-4e28-948d-f24b4d9c1acd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column required_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: aaba0541-7e5e-46d5-b440-2b990520fc06
		summarizeBy: none
		sourceColumn: required_date

		variation Variation
			isDefault
			relationship: ce513a8a-b3ec-4b0d-9c2d-fa064e28e209
			defaultHierarchy: LocalDateTable_19f3922b-e54c-41c3-9809-59e594c42171.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column shipped_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 064e6149-3af2-401b-938c-0b17317a4bc6
		summarizeBy: none
		sourceColumn: shipped_date

		variation Variation
			isDefault
			relationship: 87b3811a-c754-4a95-884d-239862179602
			defaultHierarchy: LocalDateTable_50b91a5a-2912-4245-b12f-57e89f789092.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ship_via
		dataType: int64
		formatString: 0
		lineageTag: 443aece3-9407-4fae-942e-f390196ee70a
		summarizeBy: none
		sourceColumn: ship_via

		annotation SummarizationSetBy = Automatic

	column freight
		dataType: double
		lineageTag: 1d0112de-d530-40f0-b0cc-2900379e00b5
		summarizeBy: sum
		sourceColumn: freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ship_name
		dataType: string
		lineageTag: f8810bb8-9bed-4d1a-8860-5939c4710419
		summarizeBy: none
		sourceColumn: ship_name

		annotation SummarizationSetBy = Automatic

	column ship_address
		dataType: string
		lineageTag: b693032b-f914-42a6-a480-50433412caee
		summarizeBy: none
		sourceColumn: ship_address

		annotation SummarizationSetBy = Automatic

	column ship_city
		dataType: string
		lineageTag: a062ebde-df5d-404d-b632-2b70f0658d1f
		dataCategory: City
		summarizeBy: none
		sourceColumn: ship_city

		annotation SummarizationSetBy = Automatic

	column ship_region
		dataType: string
		lineageTag: d58e3fb1-dd79-4d19-bd32-ce0927dc8189
		summarizeBy: none
		sourceColumn: ship_region

		annotation SummarizationSetBy = Automatic

	column ship_postal_code
		dataType: string
		lineageTag: 8be2ebfb-fc55-4d35-b87b-5d6dc0b1fab5
		summarizeBy: none
		sourceColumn: ship_postal_code

		annotation SummarizationSetBy = Automatic

	column ship_country
		dataType: string
		lineageTag: d670184e-9f87-4878-bf4a-092d5acbd562
		dataCategory: Country
		summarizeBy: none
		sourceColumn: ship_country

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents(API & "/bronze_orders")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"order_id", "customer_id", "employee_id", "order_date", "required_date", "shipped_date", "ship_via", "freight", "ship_name", "ship_address", "ship_city", "ship_region", "ship_postal_code", "ship_country"}, {"order_id", "customer_id", "employee_id", "order_date", "required_date", "shipped_date", "ship_via", "freight", "ship_name", "ship_address", "ship_city", "ship_region", "ship_postal_code", "ship_country"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"order_id", Int64.Type}, {"customer_id", type text}, {"employee_id", Int64.Type}, {"order_date", type date}, {"required_date", type date}, {"shipped_date", type date}, {"ship_via", Int64.Type}, {"freight", type number}, {"ship_name", type text}, {"ship_address", type text}, {"ship_city", type text}, {"ship_region", type text}, {"ship_postal_code", type text}, {"ship_country", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

