table region
	lineageTag: e0150e4f-fae2-40b7-847d-a9ff1aecd267

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: 65a9fc64-0d51-4002-8e5c-59ffe4c6d325
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column region_description
		dataType: string
		lineageTag: ffb0e20b-f670-4adc-94c5-576e7ee365a2
		summarizeBy: none
		sourceColumn: region_description

		annotation SummarizationSetBy = Automatic

	partition region = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents(API & "/bronze_region")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"region_id", "region_description"}, {"region_id", "region_description"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"region_id", Int64.Type}, {"region_description", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

