table suppliers
	lineageTag: eea1ab9f-d168-4ec3-a5cb-6c8b5349b2fd

	column supplier_id
		dataType: int64
		formatString: 0
		lineageTag: 4df384b7-a58c-4cdb-9f03-160176145897
		summarizeBy: none
		sourceColumn: supplier_id

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: 7f9a4a71-418d-4908-abba-16b4865d7210
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column contact_name
		dataType: string
		lineageTag: 55d9068c-c627-4e5d-a866-c767a7419911
		summarizeBy: none
		sourceColumn: contact_name

		annotation SummarizationSetBy = Automatic

	column contact_title
		dataType: string
		lineageTag: 2bdef981-6a7a-4542-b30f-856d24e8539c
		summarizeBy: none
		sourceColumn: contact_title

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: f4833573-e6d9-419f-b14d-f5ffa0a7d983
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: c1ee87a8-0be2-4c17-9e8e-c55c7cf286d5
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 0f38c3d3-98e1-450b-b00d-20f1d5ff0c14
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: f09d4902-6f6d-4886-9f3b-85601dc5dce6
		summarizeBy: none
		sourceColumn: postal_code

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 0481dcea-6394-45b8-8c0f-62d66f665c08
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: f58322e8-c8ca-48ea-a3fb-7f6232fdfe76
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column fax
		dataType: string
		lineageTag: cee49c09-5bd7-4203-915d-8d636143921a
		summarizeBy: none
		sourceColumn: fax

		annotation SummarizationSetBy = Automatic

	column homepage
		dataType: string
		lineageTag: 34b1ae0e-6fae-4d58-8ea5-e1a992dff5e5
		summarizeBy: none
		sourceColumn: homepage

		annotation SummarizationSetBy = Automatic

	partition suppliers = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents(API & "/bronze_suppliers")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"supplier_id", "company_name", "contact_name", "contact_title", "address", "city", "region", "postal_code", "country", "phone", "fax", "homepage"}, {"supplier_id", "company_name", "contact_name", "contact_title", "address", "city", "region", "postal_code", "country", "phone", "fax", "homepage"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"supplier_id", Int64.Type}, {"company_name", type text}, {"contact_name", type text}, {"contact_title", type text}, {"address", type text}, {"city", type text}, {"region", type text}, {"postal_code", type text}, {"country", type text}, {"phone", type text}, {"fax", type text}, {"homepage", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

